package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"strings"

	"github.com/dave/jennifer/jen"
	. "github.com/dave/jennifer/jen"
)

type DataGenerator interface {
	readSubDivFiles()
	writeToDataFile()
	ParseSubdivFile()
	ParseLOCODEFile()
}

type Generator struct{}

var (
	typeName = flag.String("type", "", "type name that should be processed; must be set to either subdiv or unlocode")
	files    = flag.String("files", "", "comma-separated list of file names; must be set; default source directory srcdir/generator/")
	output   = flag.String("output", "", "output file name; default srcdir/pkg/unlocode/data.go")
)

func main() {
	workingDir, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	defaultOutputPath := path.Join(workingDir, "../pkg/unlocode")
	defaultOutputFileName := "data.go"

	var outputFile string
	log.SetFlags(0)
	log.SetPrefix("generator: ")
	flag.Parse()
	if len(*typeName) == 0 {
		flag.Usage()
		log.Println("type missing")
		os.Exit(2)
	} else if len(*typeName) < 1 {
		log.Println("More than one type provided")
		flag.Usage()
		os.Exit(2)
	}

	generateType := string(*typeName)
	var fileNames []string
	if len(*files) > 0 {
		fileNames = strings.Split(*files, ",")
	}

	if len(*output) == 0 {
		outputFile = fmt.Sprintf("%s/%s", defaultOutputPath, defaultOutputFileName)
	} else {
    outputFile = *output
	}

	f := NewFile("unlocode")
	// A comment to mark the file as generated
	f.PackageComment("Code generated by generator, DO NOT EDIT.")
	switch generateType {
	case "subdiv":
		subdivLiteral := processSubdivFiles(fileNames, outputFile)
		f.Var().Id("Subdivisions").Op("=").Add(subdivLiteral)
	case "unlocode":
		processUnlocodeFiles(f, fileNames, outputFile)
	default:
		flag.Usage()
		os.Exit(2)
	}
	log.Printf("Saving file to: %s/%s", defaultOutputPath, defaultOutputFileName)
	err = f.Save(outputFile)
	if err != nil {
		// log.Fatalf("Details: %v", err)
		log.Println(err.Error())
		log.Println("erro")
	}
}

// func processSubdivFiles(fileNames []string, outputFile string) *jen.Statement {
// 	log.Printf("Processing subdiv files %+q into %s", fileNames, outputFile)
// 	subDivArray := Op(":=").Index().Id("SubDivision")
// 	for i, fileName := range fileNames {
// 		log.Printf("File %v: %s", i, fileName)
// 		b, err := os.ReadFile(fileName)
// 		if err != nil {
// 			log.Panic(fmt.Errorf("Failed processing file %v with error: %v", fileName, err))
// 		}
// 		csvReader := csv.NewReader(strings.NewReader(string(b)))
//     subDivArray.ValuesFunc(func(g *Group) {
// 		  for {
// 			  record, err := csvReader.Read()
// 			  if err == io.EOF {
// 				  log.Println("reached eof")
// 				  break
// 			  }
// 			  if err != nil {
// 				  log.Fatal(err)
// 			  }
// 			  log.Println(record)
// 			  g.Lit("test")
// 				// Dict{
// 				//   Id("CountryCode"): Lit(record[1]),
// 				//   Id("Name"):        Lit(record[2]),
// 				//   Id("Code"):        Lit(record[0] + record[1]),
// 				//   Id("Category"):    Lit(record[3]),
// 				//  }
// 		  }
// 		})
// 	}
// 	return subDivArray
// }
//
func processSubdivFiles(fileNames []string, outputFile string) *jen.Statement {
	log.Printf("Processing subdiv files %+q into %s", fileNames, outputFile)

	return Index().Id("SubDivision").ValuesFunc(func(g *Group) {
		for _, fileName := range fileNames {
			log.Printf("Reading file: %s", fileName)
			b, err := os.ReadFile(fileName)
			if err != nil {
				log.Fatalf("Failed processing file %v with error: %v", fileName, err)
			}

			csvReader := csv.NewReader(strings.NewReader(string(b)))

			for {
				record, err := csvReader.Read()
				if err == io.EOF {
					break // End of file
				}
				if err != nil {
					log.Println(err)
				}
				
				g.Values(Dict{
					Id("CountryCode"): Lit(record[0]),
					Id("Code"):        Lit(record[0] + record[1]),
					Id("Name"):        Lit(record[2]),
					Id("Category"):    Lit(record[3]),
				})
			}
		}
	})
}

func processUnlocodeFiles(f *File, fileNames []string, outputFile string) {
	log.Printf("Processing unlocode files %+q into %s", fileNames, outputFile)
}

// func buildSubDivArray () *jen.Statement {
// 	c := Id("SubDivision").Op(":=").Index().Id("SubDivision").ValuesFunc(func(g *Group) {
// 		for i := 0; i <= 5; i++ {
// 			g.Lit(i)
// 		}
// 	})
// 	return c
// }

// func readSubDivFiles() {
// 	os.ReadFile()
// }
//
// func writeDataFile() {
//
// }
//
// func ParseSubdivisionCodes() {
//
// }
//
// func ParseUnLocodeList() {
// }
