package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"strconv"
	"strings"

	"github.com/dave/jennifer/jen"
	. "github.com/dave/jennifer/jen"
)

var FunctionTypeToStringMap = map[string]string{
	"0": "UNKNOWN",
	"1": "PORT",
	"2": "RAIL_TERMINAL",
	"3": "ROAD_TERMINAL",
	"4": "AIRPORT",
	"5": "POSTAL_EXCHANGE_OFFICE",
	"6": "MULTIMODAL",
	"7": "FIXED_TRANSPORT",
	"B": "BORDER_CROSSING",
}

var StatusToStringMap = map[string]string{
	"":   "UNSET_STATUS",
	"AM": "UNKNOWN_STATUS_AM",
	"UR": "UNKNOWN_STATUS_UR",
	"AQ": "UNKNOWN_STATUS_AQ",
	"AA": "GOVERNMENT_AGENCY_APPROVED",
	"AC": "CUSTOMS_AUTHORITY_APPROVED",
	"AF": "NATIONAL_FACILITATION_BODY_APPROVED",
	"AI": "INTERNATIONAL_ORGANISATION_ADOPTED",
	"AS": "NATIONAL_STANDARDISATION_BODY_APPROVED",
	"RL": "RECOGNISED_LOCATION",
	"RN": "REQUEST_FROM_CREDIBLE_NATION_SOURCE",
	"RQ": "REQUEST_UNDER_CONSIDERATION",
	"RR": "REQUEST_REJECTED",
	"QQ": "ORIGINAL_ENTRY_NOT_VERIFIED_SINCE_DATE_INDICATED",
	"XX": "ENTRY_WILL_BE_REMOVED",
}

var (
	typeName = flag.String("type", "", "type name that should be processed; must be set to either subdivision or unlocode")
	files    = flag.String("files", "", "comma-separated list of file names; must be set; default source directory srcdir/generator/")
)

const (
	TYPE_SUBDIVISION = "subdivision"
	TYPE_UNLOCODE    = "unlocode"
)

func main() {
	workingDir, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	var (
		packageName                      = "data"
		warningComment                   = "This code is generated by a generator, DO NOT EDI THE FILES."
		defaultOutputPath                = path.Join(workingDir, "./pkg/data")
		defaultSubdivisionOutputFileName = "subdivision_data.go"
		defaultUnLocodeOutputFileName    = "unlocode_data.go"
	)

	var outputFile string
	log.SetFlags(0)
	log.SetPrefix("generator: ")
	flag.Parse()
	if len(*typeName) == 0 {
		flag.Usage()
		log.Println("type missing")
		os.Exit(2)
	} else if len(*typeName) < 1 {
		log.Println("More than one type provided")
		flag.Usage()
		os.Exit(2)
	}

	generateType := string(*typeName)
	var fileNames []string
	if len(*files) > 0 {
		fileNames = strings.Split(*files, ",")
	}

	f := NewFile(packageName)
	f.PackageComment(warningComment)
	switch generateType {
	case TYPE_SUBDIVISION:
		outputFile = fmt.Sprintf("%s/%s", defaultOutputPath, defaultSubdivisionOutputFileName)
		subdivLiteral := processSubdivFiles(fileNames, outputFile)
		f.Var().Id("Subdivisions").Op("=").Add(subdivLiteral)
	case TYPE_UNLOCODE:
		outputFile = fmt.Sprintf("%s/%s", defaultOutputPath, defaultUnLocodeOutputFileName)
		unlocodeLiteral := processUnlocodeFiles(fileNames, outputFile)
		f.Var().Id("Unlocodes").Op("=").Add(unlocodeLiteral)
	default:
		flag.Usage()
		os.Exit(2)
	}
	log.Printf("Updating file: %s", outputFile)
	err = f.Save(outputFile)
	if err != nil {
		log.Fatalf("Details: %v", err)
	}
}

func rowCount(fileName string) (sliceLength int) {
	log.Printf("Counting lines file: %s", fileName)
	c, err := os.ReadFile(fileName)
	if err != nil {
		log.Fatalf("Failed processing file %v with error: %v", fileName, err)
	}
	csvReader := csv.NewReader(strings.NewReader(string(c)))
	filedata, err := csvReader.ReadAll()
	if err != nil {
		log.Println(err)
	}
	sliceLength = len(filedata)
	log.Printf("Slice length: %v", sliceLength)
	return sliceLength
}

func processSubdivFiles(fileNames []string, outputFile string) *jen.Statement {
	log.Printf("Processing subdiv files %+q into %s", fileNames, outputFile)
	var sliceLength int
	for _, fileName := range fileNames {
		sliceLength = sliceLength + rowCount(fileName)
	}
	return Index(Lit(sliceLength)).Id("Subdivision").ValuesFunc(func(g *Group) {
		for _, fileName := range fileNames {
			log.Printf("Reading file: %s", fileName)
			b, err := os.ReadFile(fileName)
			if err != nil {
				log.Fatalf("Failed processing file %v with error: %v", fileName, err)
			}

			csvReader := csv.NewReader(strings.NewReader(string(b)))

			for {
				record, err := csvReader.Read()
				if err == io.EOF {
					break // End of file
				}
				if err != nil {
					log.Println(err)
				}

				g.Values(Dict{
					Id("CountryCode"): Lit(record[0]),
					Id("Code"):        Lit(record[0] + record[1]),
					Id("Name"):        Lit(record[2]),
					Id("Category"):    Lit(record[3]),
				})
			}
		}
	})
}

func processUnlocodeFiles(fileNames []string, outputFile string) *jen.Statement {
	log.Printf("Processing unlocode files %+q into %s", fileNames, outputFile)
	var sliceLength int
	for _, fileName := range fileNames {
		sliceLength = sliceLength + rowCount(fileName)
	}

	return Index(Lit(sliceLength)).Id("Unlocode").ValuesFunc(func(g *Group) {
		for _, fileName := range fileNames {
			log.Printf("Reading file: %s", fileName)
			b, err := os.ReadFile(fileName)
			if err != nil {
				log.Fatalf("Failed processing file %v with error: %v", fileName, err)
			}
			csvReader := csv.NewReader(strings.NewReader(string(b)))
			for {
				record, err := csvReader.Read()
				if err == io.EOF {
					break
				}
				if err != nil {
					log.Println(err)
				}
				functionsLit := Op("&").Index().Id("Function").ValuesFunc(func(g *Group) {
					for _, function := range record[6] {
						s := string(function)
						if s != "" && s != "-" {
							g.Id(FunctionTypeToStringMap[s])
						}
					}
				})
				var coordinatesLit *Statement
				if record[10] != "" {
					Latitude, err := strconv.ParseFloat(record[10][0:4], 64)
					if err != nil {
						log.Fatal(err)
					}
					Longtitude, err := strconv.ParseFloat(record[10][6:11], 64)
					if err != nil {
						log.Fatal(err)
					}
					coordinatesLit = Id("Point").Values(Dict{
						Id("Latitude"):   Lit(Latitude),
						Id("Longtitude"): Lit(Longtitude),
					})
				}

				var statusStrIdentifier *Statement
				statusStr := StatusToStringMap[record[7]]
				if statusStr != "" {
					statusStrIdentifier = Id(StatusToStringMap[record[7]])
				} else {
					statusStrIdentifier = Id("UNKNOWN")
				}

				g.Values(Dict{
					Id("ChangeIndicator"):  Lit(record[0]),
					Id("LoCode"):           Lit(record[1] + record[2]),
					Id("Name"):             Lit(record[3]),
					Id("NameWoDiacritics"): Lit(record[4]),
					Id("SubDiv"):           Lit(record[5]),
					Id("Function"):         functionsLit,
					Id("Status"):           statusStrIdentifier,
					Id("Date"):             Lit(record[8]),
					Id("IATA"):             Lit(record[9]),
					Id("Coordinates"):      coordinatesLit,
					Id("Remarks"):          Lit(record[11]),
				})
			}
		}
	})
}
